app:
  title: Tensure Backstage App
  listen:
    host: 0.0.0.0
    port: 7007
  baseUrl: https://backstage1.ioinfo.shop

organization:
  name: Tensure

backend:
  auth:
    keys:
      - secret: ${BACKSTAGE_BACKEND_AUTH}
  baseUrl: https://backstage1.ioinfo.shop
  listen:
    port: 7007
    host: 0.0.0.0

  csp:
    connect-src: ["'self'", 'http:', 'https:']

  cors:
    origin: https://backstage1.ioinfo.shop
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  database:
    client: pg
    connection:
      host: ${BACKSTAGE_DB_CLOUD_SQL_IP}
      port: 5432
      user: backstage
      password: ${BACKSTAGE_DB_PASSWORD}
      

