integrations:
  github:
    - host: github.com
      token: ${BACKSTAGE_GITHUB_KEY}

proxy:

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  environment: production
  providers:
    google:
      production:
        clientId: ${BACKSTAGE_CLIENT_ID}
        clientSecret: ${BACKSTAGE_CLIENT_SECRET}
        ## uncomment to set lifespan of user session
        # sessionDuration: { hours: 24 } # supports `ms` library format (e.g. '24h', '2 days'), ISO duration, "human duration" as used in code
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/google/provider#resolvers for more resolvers
            - resolver: emailMatchingUserEntityProfileEmail
scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Template, User, Group, Component, System, API, Resource, Location]
  locations:
    - type: file
      target: /app/entities/users.yaml

    - type: file
      target: /app/entities/groups.yaml

    - type: url
      target: https://github.com/VamsiKrishna082/backstage-software-templates/blob/main/template.yaml
      rules:
        - allow: [Template]

  useUrlReadersSearch: true

permission:
  # setting this to `false` will disable permissions
  enabled: true
